# Generated by Django 6.1.1 on 2026-09-20 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('superficie', models.FloatField(blank=True, help_text='En hectares', null=True)),
                ('culture', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidite_sol', models.FloatField(help_text='Pourcentage')),
                ('temperature', models.FloatField(help_text='Degrés Celsius')),
                ('humidite_air', models.FloatField(help_text='Pourcentage')),
                ('ph_sol', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='irrigation.parcelle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='irrigation.parcelle')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EtatParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iot_connecte', models.BooleanField(default=True)),
                ('irrigation_active', models.BooleanField(default=False)),
                ('irrigation_demarree_a', models.DateTimeField(blank=True, null=True)),
                ('drainage_actif', models.BooleanField(default=False)),
                ('drainage_demarre_a', models.DateTimeField(blank=True, null=True)),
                ('parcelle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etat', to='irrigation.parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('irrigation', 'Irrigation'), ('drainage', 'Drainage')], max_length=20)),
                ('statut', models.CharField(choices=[('demarrage', 'Démarrage'), ('arret', 'Arrêt')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='irrigation.parcelle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
