# Generated by Django 6.1.1 on 2026-09-16 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Parcelle Odza', max_length=100)),
                ('superficie', models.FloatField(blank=True, help_text='En hectares', null=True)),
                ('culture', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidite_sol', models.FloatField(help_text='Pourcentage')),
                ('temperature', models.FloatField(help_text='Degrés Celsius')),
                ('humidite_air', models.FloatField(help_text='Pourcentage')),
                ('ph_sol', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='irrigation.parcelle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EtatIrrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('auto', 'Automatique'), ('manuel', 'Manuel')], default='auto', max_length=10)),
                ('demarre_a', models.DateTimeField(blank=True, null=True)),
                ('duree_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('parcelle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etat_irrigation', to='irrigation.parcelle')),
            ],
        ),
    ]
